### ISSUE TITLE
react와 redux 예제 학습

### ISSUE THREAD

**Issue by Junnie-Jobs** [NHNNEXT/2016-REAL-NEXTSTEP#1]

**Comment by Byeol** [comment]
React와 Redux를 같이 사용하는 예제는 [Examples](http://redux.js.org/docs/introduction/Examples.html)를 참고하시면 좋을 것 같아요!

**Comment by Junnie-Jobs** [comment]
react학습하기에 좋은 웹페이지가 있습니다. 연규는 참고하면 좋을 듯~~ https://velopert.com/775
